### ISSUE TITLE
Cannot view submitted jobs in Eclipse

### ISSUE THREAD

**Issue by c-oberle** [boalang/xtext-ide#4] opened 2015-12-09 18:19 UTC
When running Boa code from Eclipse, a dialog shows up stating that the job submission failed. It tells to verify the Boa username/password, although they are correctly provided. The job is nevertheless submitted and the result is listed in the web interface. However, the job list in Eclipse remains empty (and nothing changes when selecting 'Boa' > 'View Submitted Jobs').

When the dialog appears, no entry is added to the error log.

The error occurred under OS X 10.10.5 with Eclipse Mars.1 Release (4.5.1).
![error-message](https://cloud.githubusercontent.com/assets/8625333/11693654/5527dde2-9ea6-11e5-88a1-9c0c30f6598f.png)

**Comment by psybers** [comment] 2015-12-09 18:58
The error about invalid date is coming from the API's Util.java where it tries to parse the date string into a Date object.

``` java
 55     private static final DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss Z");
 56 
 57     private static Date strToDate(final String s) throws BoaException {
 58         try {
 59             return df.parse(s);
 60         } catch (final ParseException e) {
 61             throw new BoaException("Invalid date '" + s + "' from server.", e);
 62         }
 63     }
```

I think the problem is the use of a capital-Z instead of lowercase-z in the format string.  I temporarily changed the date format coming from the server - can you @c-oberle please try it now and see if it works?

**Comment by c-oberle** [comment] 2015-12-09 19:12
Now it seems to work fine. No error message appears and I can see my recently submitted jobs.

**Comment by psybers** [comment] 2015-12-09 19:17
Ok great, so that was definitely the problem!  I will test to ensure I didn't break anyone else's IDE with that fix but hopefully moving forward it continues to work for you.  As such I'll close this issue.

**Closed as completed by psybers** 2015-12-09 19:17 UTC
Labels: bug
